---
ID: "425d0e8a-a850-4372-8ccd-e81e7a6e5fd6"
Parent: "ca57ba97-2a7b-4e69-b611-41adf985e43a"
Template: "ca57ba97-2a7b-4e69-b611-41adf985e43a"
Path: "/sitecore/templates/Project/automobile/Footer Templates/Footer/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
