---
ID: "2e526214-1dd7-4c87-a7af-c22c177b54a1"
Parent: "b83dcaf5-2454-4986-9094-1ef5d7ea2fa7"
Template: "b83dcaf5-2454-4986-9094-1ef5d7ea2fa7"
Path: /sitecore/templates/Project/brother/PromoStrip Templates/PromoStrip/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
