---
ID: "d7366e4f-712f-428e-8b8d-2b35961d3211"
Parent: "0de43198-1195-4e64-90e5-5bbe93090c5f"
Template: "0de43198-1195-4e64-90e5-5bbe93090c5f"
Path: /sitecore/templates/Project/sitecoresilver/Headless Tenant/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260603T231338Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sumith.damodaran@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sumith.damodaran@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b92f8ee5-8bb5-4023-b674-21deee8e858c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sumith.damodaran@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260603T231338Z
