---
ID: "ec6dbf28-b89d-4b72-962f-8c07e2428933"
Parent: "d8f2435c-c74e-46cd-9582-a238e7ea92ea"
Template: "d8f2435c-c74e-46cd-9582-a238e7ea92ea"
Path: /sitecore/templates/Project/lyveragroup/Page Design Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {D8F2435C-C74E-46CD-9582-A238E7EA92EA}
    {1105B8F8-1E00-426B-BF1F-C840742D827B}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "c9edfa91-923a-4415-9d15-faf3761b16b7"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260613T132708Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sumith.damodaran@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sumith.damodaran@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3ee1de56-c749-49f0-bb99-34d5bf50198d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sumith.damodaran@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260613T132716Z
