---
ID: "3a66d0cc-c943-42fc-b901-fd9b75a6d342"
Parent: "a5a1c65d-fdd5-4cc9-81d2-cebd883cd012"
Template: "a5a1c65d-fdd5-4cc9-81d2-cebd883cd012"
Path: /sitecore/templates/Project/brother/CampaignLanding Templates/CampaignLanding/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
