---
ID: "d0785eef-3e71-4a1f-8fde-29837b0d0a3c"
Parent: "f8df8f11-f7ba-49d2-9bba-115fd7efd37f"
Template: "f8df8f11-f7ba-49d2-9bba-115fd7efd37f"
Path: "/sitecore/templates/Project/university/CourseListing Templates/CourseListing/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
