---
ID: "f8c68db1-4d4b-41b8-a948-7ffd1d350668"
Parent: "f7dfdbf6-052c-4a6e-9663-0200f6645bb6"
Template: "f7dfdbf6-052c-4a6e-9663-0200f6645bb6"
Path: "/sitecore/templates/Project/automobile/ModelFamilySection Templates/ModelFamilySection Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
