---
ID: "5fa5ed08-145f-4b25-afdb-de9b75f4b0a7"
Parent: "9e777f9f-bc56-42f7-9708-ff8abad4256c"
Template: "9e777f9f-bc56-42f7-9708-ff8abad4256c"
Path: "/sitecore/templates/Project/automobile/Promo Templates/Promo Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
