// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import Link from 'next/link';
import { useRouter } from 'next/router';
import { TRENDING_CHIPS, STORY, EDITS, BODY_FITS, cidFromQuery } from '@/lib/asos-journey';
import { parseMarketPath, withMarket, formatMoney, sizeLabel, MARKETS } from '@/lib/asos-market';
import { Link as Link_8a80e63291fea86e0744df19113dc44bec187216, Text, useSitecore, NextImage, Placeholder, RichText, Image, CdpHelper, withDatasourceCheck } from '@sitecore-content-sdk/nextjs';
import { useMemo, useId, useState, useEffect, useRef, useCallback } from 'react';
import React from 'react';
import * as React_7214d18997ee864dd178de7b3a8430f6783e8b89 from 'react';
import Head from 'next/head';
import { PRODUCTS, productImage, alsoBought, HERO_PRODUCT, lookFor, productFromPath, productGallery, categoryFromPath, productsForCid } from '@/lib/product-catalog';
import { faFacebookF, faInstagram, faLinkedin, faTwitter, faYoutube } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { Swiper, SwiperSlide } from 'swiper/react';
import { A11y, Keyboard, Navigation, Pagination, Autoplay } from 'swiper/modules';
import { ChevronLeft, ChevronRight, Search, Heart, Loader2, Check, Plus, Star, X, User, ShoppingCart, ArrowLeft, Globe, ShoppingBag, MessageCircle, Send } from 'lucide-react';
import { filterSearchHits } from '@/lib/asos-search';
import { recordSearchEvent, affinitiesForPath, getGuestName, getSessionEvents, getSessionRef, getVisitCount, identifyGuest, recordPageView, recordVisitOnce } from '@/lib/cdp/cdp-session-tracker';
import { ProductCard } from 'src/components/non-sitecore/ProductCard';
import { savedProducts, isSaved, toggleSave, readBoard, curationStats } from '@/lib/asos-save';
import { AsosProductCard } from '@/components/non-sitecore/AsosProductCard';
import { fieldString } from '@/lib/sitecore-fields';
import { addToBag, bagLines } from '@/lib/asos-bag';
import InfiniteScroll from '@/shadcn/components/ui/infiniteScroll';
import { ProductCard as ProductCard_f5c29266c91cfe4f66c8f4e91c1fad0bbbe159f9 } from '@/components/non-sitecore/ProductCard';
import { useI18n } from 'next-localization';
import { isParamEnabled } from '@/helpers/isParamEnabled';
import QuantityControl from 'src/components/non-sitecore/QuantityControl';
import { ProductGallery } from 'src/components/non-sitecore/ProductGallery';
import { ProductMetaDetals } from 'src/components/non-sitecore/ProductMetaDetails';
import { ProductSizeControl } from 'src/components/non-sitecore/ProductSizeControl';
import { ProductColorControl } from 'src/components/non-sitecore/ProductColorControl';
import { AddToCartButton } from 'src/components/non-sitecore/AddToCartButton';
import { useLocale } from '@/hooks/useLocaleOptions';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/shadcn/components/ui/accordion';
import { ParentPathLink } from 'src/components/non-sitecore/ParentPathLink';
import { ProductReviews } from 'src/components/non-sitecore/ProductReviews';
import StarRating from 'src/components/non-sitecore/StarRating';
import { usePathname } from 'next/navigation';
import { useCartAction } from '@/hooks/useCartAction';
import { getCart } from '@/lib/cart';
import { DrawerClose, Drawer, DrawerContent, DrawerTrigger } from '@/shadcn/components/ui/drawer';
import { MiniCart } from 'src/components/non-sitecore/MiniCart';
import { useClickAway } from '@/hooks/useClickAway';
import { useStopResponsiveTransition } from '@/hooks/useStopResponsiveTransition';
import { extractMediaUrl } from '@/helpers/extractMediaUrl';
import { getLinkContent, getLinkField, isNavLevel, isNavRootItem, prepareFields } from '@/helpers/navHelpers';
import clsx from 'clsx';
import { localeOptions } from '@/constants/localeOptions';
import { DAM } from '@/lib/dam-registry';
import { HeaderSearch } from '@/lib/HeaderSearch';
import client from 'lib/sitecore-client';
import Image_5d8ce56058442d94361877e28c501c951a554a6a from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import { CdpPageViewTracker } from '@/components/cdp-profile-panel/CdpPageViewTracker';
import { CdpProfilePanel } from '@/components/cdp-profile-panel/CdpProfilePanel';
import { answerChat, suggestedPrompts } from '@/lib/chat-knowledge';

const importMap = [
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link },
    ]
  },
  {
    module: 'next/router',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: '@/lib/asos-journey',
    exports: [
      { name: 'TRENDING_CHIPS', value: TRENDING_CHIPS },
      { name: 'STORY', value: STORY },
      { name: 'EDITS', value: EDITS },
      { name: 'BODY_FITS', value: BODY_FITS },
      { name: 'cidFromQuery', value: cidFromQuery },
    ]
  },
  {
    module: '@/lib/asos-market',
    exports: [
      { name: 'parseMarketPath', value: parseMarketPath },
      { name: 'withMarket', value: withMarket },
      { name: 'formatMoney', value: formatMoney },
      { name: 'sizeLabel', value: sizeLabel },
      { name: 'MARKETS', value: MARKETS },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link_8a80e63291fea86e0744df19113dc44bec187216 },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'NextImage', value: NextImage },
      { name: 'Placeholder', value: Placeholder },
      { name: 'RichText', value: RichText },
      { name: 'Image', value: Image },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useMemo', value: useMemo },
      { name: 'useId', value: useId },
      { name: 'useState', value: useState },
      { name: 'useEffect', value: useEffect },
      { name: 'useRef', value: useRef },
      { name: 'useCallback', value: useCallback },
      { name: 'default', value: React },
      { name: '*', value: React_7214d18997ee864dd178de7b3a8430f6783e8b89 },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: '@/lib/product-catalog',
    exports: [
      { name: 'PRODUCTS', value: PRODUCTS },
      { name: 'productImage', value: productImage },
      { name: 'alsoBought', value: alsoBought },
      { name: 'HERO_PRODUCT', value: HERO_PRODUCT },
      { name: 'lookFor', value: lookFor },
      { name: 'productFromPath', value: productFromPath },
      { name: 'productGallery', value: productGallery },
      { name: 'categoryFromPath', value: categoryFromPath },
      { name: 'productsForCid', value: productsForCid },
    ]
  },
  {
    module: '@fortawesome/free-brands-svg-icons',
    exports: [
      { name: 'faFacebookF', value: faFacebookF },
      { name: 'faInstagram', value: faInstagram },
      { name: 'faLinkedin', value: faLinkedin },
      { name: 'faTwitter', value: faTwitter },
      { name: 'faYoutube', value: faYoutube },
    ]
  },
  {
    module: '@fortawesome/react-fontawesome',
    exports: [
      { name: 'FontAwesomeIcon', value: FontAwesomeIcon },
    ]
  },
  {
    module: 'swiper/react',
    exports: [
      { name: 'Swiper', value: Swiper },
      { name: 'SwiperSlide', value: SwiperSlide },
    ]
  },
  {
    module: 'swiper/modules',
    exports: [
      { name: 'A11y', value: A11y },
      { name: 'Keyboard', value: Keyboard },
      { name: 'Navigation', value: Navigation },
      { name: 'Pagination', value: Pagination },
      { name: 'Autoplay', value: Autoplay },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'ChevronLeft', value: ChevronLeft },
      { name: 'ChevronRight', value: ChevronRight },
      { name: 'Search', value: Search },
      { name: 'Heart', value: Heart },
      { name: 'Loader2', value: Loader2 },
      { name: 'Check', value: Check },
      { name: 'Plus', value: Plus },
      { name: 'Star', value: Star },
      { name: 'X', value: X },
      { name: 'User', value: User },
      { name: 'ShoppingCart', value: ShoppingCart },
      { name: 'ArrowLeft', value: ArrowLeft },
      { name: 'Globe', value: Globe },
      { name: 'ShoppingBag', value: ShoppingBag },
      { name: 'MessageCircle', value: MessageCircle },
      { name: 'Send', value: Send },
    ]
  },
  {
    module: '@/lib/asos-search',
    exports: [
      { name: 'filterSearchHits', value: filterSearchHits },
    ]
  },
  {
    module: '@/lib/cdp/cdp-session-tracker',
    exports: [
      { name: 'recordSearchEvent', value: recordSearchEvent },
      { name: 'affinitiesForPath', value: affinitiesForPath },
      { name: 'getGuestName', value: getGuestName },
      { name: 'getSessionEvents', value: getSessionEvents },
      { name: 'getSessionRef', value: getSessionRef },
      { name: 'getVisitCount', value: getVisitCount },
      { name: 'identifyGuest', value: identifyGuest },
      { name: 'recordPageView', value: recordPageView },
      { name: 'recordVisitOnce', value: recordVisitOnce },
    ]
  },
  {
    module: 'src/components/non-sitecore/ProductCard',
    exports: [
      { name: 'ProductCard', value: ProductCard },
    ]
  },
  {
    module: '@/lib/asos-save',
    exports: [
      { name: 'savedProducts', value: savedProducts },
      { name: 'isSaved', value: isSaved },
      { name: 'toggleSave', value: toggleSave },
      { name: 'readBoard', value: readBoard },
      { name: 'curationStats', value: curationStats },
    ]
  },
  {
    module: '@/components/non-sitecore/AsosProductCard',
    exports: [
      { name: 'AsosProductCard', value: AsosProductCard },
    ]
  },
  {
    module: '@/lib/sitecore-fields',
    exports: [
      { name: 'fieldString', value: fieldString },
    ]
  },
  {
    module: '@/lib/asos-bag',
    exports: [
      { name: 'addToBag', value: addToBag },
      { name: 'bagLines', value: bagLines },
    ]
  },
  {
    module: '@/shadcn/components/ui/infiniteScroll',
    exports: [
      { name: 'default', value: InfiniteScroll },
    ]
  },
  {
    module: '@/components/non-sitecore/ProductCard',
    exports: [
      { name: 'ProductCard', value: ProductCard_f5c29266c91cfe4f66c8f4e91c1fad0bbbe159f9 },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: '@/helpers/isParamEnabled',
    exports: [
      { name: 'isParamEnabled', value: isParamEnabled },
    ]
  },
  {
    module: 'src/components/non-sitecore/QuantityControl',
    exports: [
      { name: 'default', value: QuantityControl },
    ]
  },
  {
    module: 'src/components/non-sitecore/ProductGallery',
    exports: [
      { name: 'ProductGallery', value: ProductGallery },
    ]
  },
  {
    module: 'src/components/non-sitecore/ProductMetaDetails',
    exports: [
      { name: 'ProductMetaDetals', value: ProductMetaDetals },
    ]
  },
  {
    module: 'src/components/non-sitecore/ProductSizeControl',
    exports: [
      { name: 'ProductSizeControl', value: ProductSizeControl },
    ]
  },
  {
    module: 'src/components/non-sitecore/ProductColorControl',
    exports: [
      { name: 'ProductColorControl', value: ProductColorControl },
    ]
  },
  {
    module: 'src/components/non-sitecore/AddToCartButton',
    exports: [
      { name: 'AddToCartButton', value: AddToCartButton },
    ]
  },
  {
    module: '@/hooks/useLocaleOptions',
    exports: [
      { name: 'useLocale', value: useLocale },
    ]
  },
  {
    module: '@/shadcn/components/ui/accordion',
    exports: [
      { name: 'Accordion', value: Accordion },
      { name: 'AccordionContent', value: AccordionContent },
      { name: 'AccordionItem', value: AccordionItem },
      { name: 'AccordionTrigger', value: AccordionTrigger },
    ]
  },
  {
    module: 'src/components/non-sitecore/ParentPathLink',
    exports: [
      { name: 'ParentPathLink', value: ParentPathLink },
    ]
  },
  {
    module: 'src/components/non-sitecore/ProductReviews',
    exports: [
      { name: 'ProductReviews', value: ProductReviews },
    ]
  },
  {
    module: 'src/components/non-sitecore/StarRating',
    exports: [
      { name: 'default', value: StarRating },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'usePathname', value: usePathname },
    ]
  },
  {
    module: '@/hooks/useCartAction',
    exports: [
      { name: 'useCartAction', value: useCartAction },
    ]
  },
  {
    module: '@/lib/cart',
    exports: [
      { name: 'getCart', value: getCart },
    ]
  },
  {
    module: '@/shadcn/components/ui/drawer',
    exports: [
      { name: 'DrawerClose', value: DrawerClose },
      { name: 'Drawer', value: Drawer },
      { name: 'DrawerContent', value: DrawerContent },
      { name: 'DrawerTrigger', value: DrawerTrigger },
    ]
  },
  {
    module: 'src/components/non-sitecore/MiniCart',
    exports: [
      { name: 'MiniCart', value: MiniCart },
    ]
  },
  {
    module: '@/hooks/useClickAway',
    exports: [
      { name: 'useClickAway', value: useClickAway },
    ]
  },
  {
    module: '@/hooks/useStopResponsiveTransition',
    exports: [
      { name: 'useStopResponsiveTransition', value: useStopResponsiveTransition },
    ]
  },
  {
    module: '@/helpers/extractMediaUrl',
    exports: [
      { name: 'extractMediaUrl', value: extractMediaUrl },
    ]
  },
  {
    module: '@/helpers/navHelpers',
    exports: [
      { name: 'getLinkContent', value: getLinkContent },
      { name: 'getLinkField', value: getLinkField },
      { name: 'isNavLevel', value: isNavLevel },
      { name: 'isNavRootItem', value: isNavRootItem },
      { name: 'prepareFields', value: prepareFields },
    ]
  },
  {
    module: 'clsx',
    exports: [
      { name: 'default', value: clsx },
    ]
  },
  {
    module: '@/constants/localeOptions',
    exports: [
      { name: 'localeOptions', value: localeOptions },
    ]
  },
  {
    module: '@/lib/dam-registry',
    exports: [
      { name: 'DAM', value: DAM },
    ]
  },
  {
    module: '@/lib/HeaderSearch',
    exports: [
      { name: 'HeaderSearch', value: HeaderSearch },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image_5d8ce56058442d94361877e28c501c951a554a6a },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: '@/components/cdp-profile-panel/CdpPageViewTracker',
    exports: [
      { name: 'CdpPageViewTracker', value: CdpPageViewTracker },
    ]
  },
  {
    module: '@/components/cdp-profile-panel/CdpProfilePanel',
    exports: [
      { name: 'CdpProfilePanel', value: CdpProfilePanel },
    ]
  },
  {
    module: '@/lib/chat-knowledge',
    exports: [
      { name: 'answerChat', value: answerChat },
      { name: 'suggestedPrompts', value: suggestedPrompts },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
