---
ID: "6b376de5-073e-4651-821d-c8f1fa212084"
Parent: "8fd458d0-8c78-43ac-a493-16b1e3cacc44"
Template: "8fd458d0-8c78-43ac-a493-16b1e3cacc44"
Path: "/sitecore/templates/Project/automobile/Header Templates/Header Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
