#!/usr/bin/env sh
set -e
set -o pipefail

# Explicitly go to the luxury-retail folder from the git root
cd "$(git rev-parse --show-toplevel)/industry-verticals/luxury-retail"

# (optional) trace
echo ">> pre-commit running in $(pwd)"

# run your checks
npx tsc -p tsconfig.json --noEmit
npx lint-staged