---
ID: "d5cfc64d-ea7a-4cc3-90ae-7d058aa51acc"
Parent: "4237fa0f-dbee-429e-829b-7ff874fc8bca"
Template: "4237fa0f-dbee-429e-829b-7ff874fc8bca"
Path: "/sitecore/templates/Project/brother/RelatedProducts Templates/RelatedProducts/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
