---
ID: "14d6acae-a7f8-465f-9c47-3ef7485af308"
Parent: "805a3737-055e-40ae-96a8-c5391bfc0ba3"
Template: "805a3737-055e-40ae-96a8-c5391bfc0ba3"
Path: "/sitecore/templates/Project/brother/ProductListing Templates/ProductListing/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
