---
ID: "9849e7a4-ed99-4002-b6ec-81483085d013"
Parent: "82f6bb06-895c-4f11-8a93-36dcd93dc2fb"
Template: "82f6bb06-895c-4f11-8a93-36dcd93dc2fb"
Path: "/sitecore/templates/Project/university/CourseListing Templates/CourseListing Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {F8DF8F11-F7BA-49D2-9BBA-115FD7EFD37F}
    {82F6BB06-895C-4F11-8A93-36DCD93DC2FB}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
