---
ID: "6116dcc4-9bb5-43e4-9c3f-bfa4e685e507"
Parent: "1a500a49-db30-4657-b6ea-d5c799adebb4"
Template: "1a500a49-db30-4657-b6ea-d5c799adebb4"
Path: "/sitecore/templates/Project/brother/PromoGrid Templates/PromoGrid Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
