// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { Link, Text, useSitecore, RichText, Image, Placeholder, NextImage, DateField, CdpHelper, withDatasourceCheck } from '@sitecore-content-sdk/nextjs';
import { useMemo, useState, useRef, useEffect, useCallback } from 'react';
import React from 'react';
import Head from 'next/head';
import { faFacebookF, faInstagram, faLinkedinIn, faTwitter, faYoutube } from '@fortawesome/free-brands-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { ArrowRight, Share2, ChevronLeft, Calendar, User, ArrowLeft, X, Menu, Activity, Thermometer, TrendingDown, TrendingUp, Unplug, Zap, Loader2, Bookmark } from 'lucide-react';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import { useI18n } from 'next-localization';
import { LayoutStyles } from '@/types/styleFlags';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/shadcn/components/ui/dropdown-menu';
import { EmailIcon, EmailShareButton, FacebookIcon, FacebookShareButton, LinkedinIcon, LinkedinShareButton, PinterestIcon, PinterestShareButton, TwitterIcon, TwitterShareButton } from 'react-share';
import { usePathname } from 'next/navigation';
import { newsDateFormatter } from '@/helpers/dateHelper';
import { useClickAway } from '@/hooks/useClickAway';
import { useStopResponsiveTransition } from '@/hooks/useStopResponsiveTransition';
import { extractMediaUrl } from '@/helpers/extractMediaUrl';
import { getLinkContent, getLinkField, isNavLevel, isNavRootItem, prepareFields } from '@/helpers/navHelpers';
import clsx from 'clsx';
import { isParamEnabled } from '@/helpers/isParamEnabled';
import { Drawer, DrawerTrigger, DrawerContent, DrawerClose } from '@/shadcn/components/ui/drawer';
import { Progress } from '@/shadcn/components/ui/progress';
import { GRID_CONDITIONS_DATA } from 'src/components/grid-conditions/gridData';
import client from 'lib/sitecore-client';
import Image_5d8ce56058442d94361877e28c501c951a554a6a from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import { getArticlesCountsByCategory } from '@/helpers/articleHelpers';
import InfiniteScroll from '@/shadcn/components/ui/infiniteScroll';
import ArticleCard from 'src/components/non-sitecore/ArticleCard';
import { ParentPathLink } from 'src/components/non-sitecore/ParentPathLink';
import SocialShare from 'src/components/non-sitecore/SocialShare';

const importMap = [
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'RichText', value: RichText },
      { name: 'Image', value: Image },
      { name: 'Placeholder', value: Placeholder },
      { name: 'NextImage', value: NextImage },
      { name: 'DateField', value: DateField },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useMemo', value: useMemo },
      { name: 'useState', value: useState },
      { name: 'useRef', value: useRef },
      { name: 'useEffect', value: useEffect },
      { name: 'useCallback', value: useCallback },
      { name: 'default', value: React },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: '@fortawesome/free-brands-svg-icons',
    exports: [
      { name: 'faFacebookF', value: faFacebookF },
      { name: 'faInstagram', value: faInstagram },
      { name: 'faLinkedinIn', value: faLinkedinIn },
      { name: 'faTwitter', value: faTwitter },
      { name: 'faYoutube', value: faYoutube },
    ]
  },
  {
    module: '@fortawesome/react-fontawesome',
    exports: [
      { name: 'FontAwesomeIcon', value: FontAwesomeIcon },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'ArrowRight', value: ArrowRight },
      { name: 'Share2', value: Share2 },
      { name: 'ChevronLeft', value: ChevronLeft },
      { name: 'Calendar', value: Calendar },
      { name: 'User', value: User },
      { name: 'ArrowLeft', value: ArrowLeft },
      { name: 'X', value: X },
      { name: 'Menu', value: Menu },
      { name: 'Activity', value: Activity },
      { name: 'Thermometer', value: Thermometer },
      { name: 'TrendingDown', value: TrendingDown },
      { name: 'TrendingUp', value: TrendingUp },
      { name: 'Unplug', value: Unplug },
      { name: 'Zap', value: Zap },
      { name: 'Loader2', value: Loader2 },
      { name: 'Bookmark', value: Bookmark },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: '@/types/styleFlags',
    exports: [
      { name: 'LayoutStyles', value: LayoutStyles },
    ]
  },
  {
    module: '@/shadcn/components/ui/dropdown-menu',
    exports: [
      { name: 'DropdownMenu', value: DropdownMenu },
      { name: 'DropdownMenuContent', value: DropdownMenuContent },
      { name: 'DropdownMenuItem', value: DropdownMenuItem },
      { name: 'DropdownMenuTrigger', value: DropdownMenuTrigger },
    ]
  },
  {
    module: 'react-share',
    exports: [
      { name: 'EmailIcon', value: EmailIcon },
      { name: 'EmailShareButton', value: EmailShareButton },
      { name: 'FacebookIcon', value: FacebookIcon },
      { name: 'FacebookShareButton', value: FacebookShareButton },
      { name: 'LinkedinIcon', value: LinkedinIcon },
      { name: 'LinkedinShareButton', value: LinkedinShareButton },
      { name: 'PinterestIcon', value: PinterestIcon },
      { name: 'PinterestShareButton', value: PinterestShareButton },
      { name: 'TwitterIcon', value: TwitterIcon },
      { name: 'TwitterShareButton', value: TwitterShareButton },
    ]
  },
  {
    module: 'next/navigation',
    exports: [
      { name: 'usePathname', value: usePathname },
    ]
  },
  {
    module: '@/helpers/dateHelper',
    exports: [
      { name: 'newsDateFormatter', value: newsDateFormatter },
    ]
  },
  {
    module: '@/hooks/useClickAway',
    exports: [
      { name: 'useClickAway', value: useClickAway },
    ]
  },
  {
    module: '@/hooks/useStopResponsiveTransition',
    exports: [
      { name: 'useStopResponsiveTransition', value: useStopResponsiveTransition },
    ]
  },
  {
    module: '@/helpers/extractMediaUrl',
    exports: [
      { name: 'extractMediaUrl', value: extractMediaUrl },
    ]
  },
  {
    module: '@/helpers/navHelpers',
    exports: [
      { name: 'getLinkContent', value: getLinkContent },
      { name: 'getLinkField', value: getLinkField },
      { name: 'isNavLevel', value: isNavLevel },
      { name: 'isNavRootItem', value: isNavRootItem },
      { name: 'prepareFields', value: prepareFields },
    ]
  },
  {
    module: 'clsx',
    exports: [
      { name: 'default', value: clsx },
    ]
  },
  {
    module: '@/helpers/isParamEnabled',
    exports: [
      { name: 'isParamEnabled', value: isParamEnabled },
    ]
  },
  {
    module: '@/shadcn/components/ui/drawer',
    exports: [
      { name: 'Drawer', value: Drawer },
      { name: 'DrawerTrigger', value: DrawerTrigger },
      { name: 'DrawerContent', value: DrawerContent },
      { name: 'DrawerClose', value: DrawerClose },
    ]
  },
  {
    module: '@/shadcn/components/ui/progress',
    exports: [
      { name: 'Progress', value: Progress },
    ]
  },
  {
    module: 'src/components/grid-conditions/gridData',
    exports: [
      { name: 'GRID_CONDITIONS_DATA', value: GRID_CONDITIONS_DATA },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image_5d8ce56058442d94361877e28c501c951a554a6a },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: '@/helpers/articleHelpers',
    exports: [
      { name: 'getArticlesCountsByCategory', value: getArticlesCountsByCategory },
    ]
  },
  {
    module: '@/shadcn/components/ui/infiniteScroll',
    exports: [
      { name: 'default', value: InfiniteScroll },
    ]
  },
  {
    module: 'src/components/non-sitecore/ArticleCard',
    exports: [
      { name: 'default', value: ArticleCard },
    ]
  },
  {
    module: 'src/components/non-sitecore/ParentPathLink',
    exports: [
      { name: 'ParentPathLink', value: ParentPathLink },
    ]
  },
  {
    module: 'src/components/non-sitecore/SocialShare',
    exports: [
      { name: 'default', value: SocialShare },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
