// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { Link, Text, useSitecore, Placeholder, RichText, NextImage, Image, CdpHelper, withDatasourceCheck } from '@sitecore-content-sdk/nextjs';
import { useState, useRef, useCallback, useEffect, useMemo, createContext, useContext } from 'react';
import React from 'react';
import { promoFallbackImage } from '@/lib/promo-fallbacks';
import { normalizeSxaStyles } from '@/lib/sxa-styles';
import { ChevronDown, Award, Martini, Star, Ticket, ChevronLeft, ChevronRight, Maximize2, Search, ShoppingBag, User, MoreVertical, Info, X, ChevronUp, Copy, Check, Eye, RefreshCw, Target, Megaphone, RotateCcw, Loader2 } from 'lucide-react';
import HamburgerIcon from '@/components/non-sitecore/HamburgerIcon';
import { useClickAway } from '@/hooks/useClickAway';
import { useStopResponsiveTransition } from '@/hooks/useStopResponsiveTransition';
import { extractMediaUrl } from '@/helpers/extractMediaUrl';
import { getLinkContent, getLinkField, isNavLevel, isNavRootItem, prepareFields } from '@/helpers/navHelpers';
import clsx from 'clsx';
import { isParamEnabled } from '@/helpers/isParamEnabled';
import { KP_TRUST_ITEMS, KP_CATEGORY_TABS, KP_FEATURED_EVENTS, WIMBLEDON_VIDEO_TABS, KP_CONTACT_PHONE, KP_MAIN_NAV, KP_FOOTER_LINKS, WIMBLEDON_FACILITIES, KP_EXPERIENCE_FINDER, KP_ABOUT_DEFAULT, KP_HERO_DEFAULT, WIMBLEDON_EVENT_DEFAULT } from '@/lib/keith-prowse-defaults';
import { GS_TRUST_ITEMS, GS_CONTACT_PHONE, GS_MAIN_NAV, GS_UTILITY_LINKS, GS_FOOTER_LINKS } from '@/lib/gulliverstravel-defaults';
import { isGulliversTravelSite, isKeithProwseSite, demoSiteDisplayName } from '@/lib/lyveragroup-site';
import { sharedComponentModifier } from '@/lib/lyveragroup-themes';
import { textFieldValue, unwrapField, hasLinkValue, imageSrc, linkHref, linkLabel, richTextFieldValue, normalizeLinkField } from '@/lib/lyvera-field-utils';
import { LYVERA_INTRO_DEFAULT, LYVERA_BRAND_LOGO_FALLBACKS, LYVERA_MULTI_PROMO_DEFAULT, LYVERA_MULTI_PROMO_SLIDES, LYVERA_BRANDS, LYVERA_CONTACT_EMAIL, LYVERA_MAIN_NAV, LYVERA_FOOTER_LEGAL, LYVERA_FOOTER_TAGLINE, LYVERA_FOOTER_USEFUL_LINKS, LYVERA_SOCIAL, LYVERA_BANNER_WHY_DEFAULT, LYVERA_HERO_DEFAULT } from '@/lib/lyvera-defaults';
import { placeholderHasComponents, resolveChildPlaceholderKey, getPlaceholderSlots } from '@/lib/placeholder-utils';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import { LYVERA_BLOG_ARTICLES, LYVERA_BLOG_LISTING, findBlogArticleByPath } from '@/lib/lyvera-blog-content';
import { getPublicItemPath } from '@/lib/lyvera-sites';
import { findBrandPageByPath } from '@/lib/lyvera-brand-pages';
import { useDemoAuth, DEMO_EMAIL, DemoAuthProvider } from '@/lib/demo-auth';
import { DemoSiteLabelSync } from '@/components/demo/DemoSiteLabelSync';
import { HeaderDemoAuth } from '@/components/lyvera/HeaderDemoAuth';
import { LYVERA_FAQ_HEADING, LYVERA_FAQ_ITEMS } from '@/lib/lyvera-faq-content';
import { useFacilityChooserContext } from 'src/components/lyvera/LyveraFacilityChooser';
import { KP_BLOG_ARTICLES, KP_BLOG_LISTING } from '@/lib/keith-prowse-blog-content';
import { CdpSubscribeButton } from '@/components/cdp-profile-panel/CdpSubscribeButton';
import { DemoLoginModal } from '@/components/lyvera/DemoLoginModal';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import Image_5d8ce56058442d94361877e28c501c951a554a6a from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView } from '@sitecore-cloudsdk/events/browser';
import config from 'sitecore.config';
import { cn } from '@/shadcn/lib/utils';
import { displayNameFromEmail, EMAIL_REGEX, identifyVisitorByEmail } from '@/lib/cdp/cdp-identity';
import { CdpProfilePanel } from '@/components/cdp-profile-panel/CdpProfilePanel';
import { CdpPageViewTracker } from '@/components/cdp-profile-panel/CdpPageViewTracker';
import { useRouter } from 'next/router';
import { loadCdpGuestProfile } from '@/lib/cdp/cdp-cloud-context';
import { resetSitecoreVisitorSession } from '@/lib/cdp/sitecore-cookie-reset';
import { recordPageView } from '@/lib/cdp/cdp-session-tracker';

const importMap = [
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'Placeholder', value: Placeholder },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'Image', value: Image },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useState', value: useState },
      { name: 'useRef', value: useRef },
      { name: 'useCallback', value: useCallback },
      { name: 'useEffect', value: useEffect },
      { name: 'useMemo', value: useMemo },
      { name: 'createContext', value: createContext },
      { name: 'useContext', value: useContext },
      { name: 'default', value: React },
    ]
  },
  {
    module: '@/lib/promo-fallbacks',
    exports: [
      { name: 'promoFallbackImage', value: promoFallbackImage },
    ]
  },
  {
    module: '@/lib/sxa-styles',
    exports: [
      { name: 'normalizeSxaStyles', value: normalizeSxaStyles },
    ]
  },
  {
    module: 'lucide-react',
    exports: [
      { name: 'ChevronDown', value: ChevronDown },
      { name: 'Award', value: Award },
      { name: 'Martini', value: Martini },
      { name: 'Star', value: Star },
      { name: 'Ticket', value: Ticket },
      { name: 'ChevronLeft', value: ChevronLeft },
      { name: 'ChevronRight', value: ChevronRight },
      { name: 'Maximize2', value: Maximize2 },
      { name: 'Search', value: Search },
      { name: 'ShoppingBag', value: ShoppingBag },
      { name: 'User', value: User },
      { name: 'MoreVertical', value: MoreVertical },
      { name: 'Info', value: Info },
      { name: 'X', value: X },
      { name: 'ChevronUp', value: ChevronUp },
      { name: 'Copy', value: Copy },
      { name: 'Check', value: Check },
      { name: 'Eye', value: Eye },
      { name: 'RefreshCw', value: RefreshCw },
      { name: 'Target', value: Target },
      { name: 'Megaphone', value: Megaphone },
      { name: 'RotateCcw', value: RotateCcw },
      { name: 'Loader2', value: Loader2 },
    ]
  },
  {
    module: '@/components/non-sitecore/HamburgerIcon',
    exports: [
      { name: 'default', value: HamburgerIcon },
    ]
  },
  {
    module: '@/hooks/useClickAway',
    exports: [
      { name: 'useClickAway', value: useClickAway },
    ]
  },
  {
    module: '@/hooks/useStopResponsiveTransition',
    exports: [
      { name: 'useStopResponsiveTransition', value: useStopResponsiveTransition },
    ]
  },
  {
    module: '@/helpers/extractMediaUrl',
    exports: [
      { name: 'extractMediaUrl', value: extractMediaUrl },
    ]
  },
  {
    module: '@/helpers/navHelpers',
    exports: [
      { name: 'getLinkContent', value: getLinkContent },
      { name: 'getLinkField', value: getLinkField },
      { name: 'isNavLevel', value: isNavLevel },
      { name: 'isNavRootItem', value: isNavRootItem },
      { name: 'prepareFields', value: prepareFields },
    ]
  },
  {
    module: 'clsx',
    exports: [
      { name: 'default', value: clsx },
    ]
  },
  {
    module: '@/helpers/isParamEnabled',
    exports: [
      { name: 'isParamEnabled', value: isParamEnabled },
    ]
  },
  {
    module: '@/lib/keith-prowse-defaults',
    exports: [
      { name: 'KP_TRUST_ITEMS', value: KP_TRUST_ITEMS },
      { name: 'KP_CATEGORY_TABS', value: KP_CATEGORY_TABS },
      { name: 'KP_FEATURED_EVENTS', value: KP_FEATURED_EVENTS },
      { name: 'WIMBLEDON_VIDEO_TABS', value: WIMBLEDON_VIDEO_TABS },
      { name: 'KP_CONTACT_PHONE', value: KP_CONTACT_PHONE },
      { name: 'KP_MAIN_NAV', value: KP_MAIN_NAV },
      { name: 'KP_FOOTER_LINKS', value: KP_FOOTER_LINKS },
      { name: 'WIMBLEDON_FACILITIES', value: WIMBLEDON_FACILITIES },
      { name: 'KP_EXPERIENCE_FINDER', value: KP_EXPERIENCE_FINDER },
      { name: 'KP_ABOUT_DEFAULT', value: KP_ABOUT_DEFAULT },
      { name: 'KP_HERO_DEFAULT', value: KP_HERO_DEFAULT },
      { name: 'WIMBLEDON_EVENT_DEFAULT', value: WIMBLEDON_EVENT_DEFAULT },
    ]
  },
  {
    module: '@/lib/gulliverstravel-defaults',
    exports: [
      { name: 'GS_TRUST_ITEMS', value: GS_TRUST_ITEMS },
      { name: 'GS_CONTACT_PHONE', value: GS_CONTACT_PHONE },
      { name: 'GS_MAIN_NAV', value: GS_MAIN_NAV },
      { name: 'GS_UTILITY_LINKS', value: GS_UTILITY_LINKS },
      { name: 'GS_FOOTER_LINKS', value: GS_FOOTER_LINKS },
    ]
  },
  {
    module: '@/lib/lyveragroup-site',
    exports: [
      { name: 'isGulliversTravelSite', value: isGulliversTravelSite },
      { name: 'isKeithProwseSite', value: isKeithProwseSite },
      { name: 'demoSiteDisplayName', value: demoSiteDisplayName },
    ]
  },
  {
    module: '@/lib/lyveragroup-themes',
    exports: [
      { name: 'sharedComponentModifier', value: sharedComponentModifier },
    ]
  },
  {
    module: '@/lib/lyvera-field-utils',
    exports: [
      { name: 'textFieldValue', value: textFieldValue },
      { name: 'unwrapField', value: unwrapField },
      { name: 'hasLinkValue', value: hasLinkValue },
      { name: 'imageSrc', value: imageSrc },
      { name: 'linkHref', value: linkHref },
      { name: 'linkLabel', value: linkLabel },
      { name: 'richTextFieldValue', value: richTextFieldValue },
      { name: 'normalizeLinkField', value: normalizeLinkField },
    ]
  },
  {
    module: '@/lib/lyvera-defaults',
    exports: [
      { name: 'LYVERA_INTRO_DEFAULT', value: LYVERA_INTRO_DEFAULT },
      { name: 'LYVERA_BRAND_LOGO_FALLBACKS', value: LYVERA_BRAND_LOGO_FALLBACKS },
      { name: 'LYVERA_MULTI_PROMO_DEFAULT', value: LYVERA_MULTI_PROMO_DEFAULT },
      { name: 'LYVERA_MULTI_PROMO_SLIDES', value: LYVERA_MULTI_PROMO_SLIDES },
      { name: 'LYVERA_BRANDS', value: LYVERA_BRANDS },
      { name: 'LYVERA_CONTACT_EMAIL', value: LYVERA_CONTACT_EMAIL },
      { name: 'LYVERA_MAIN_NAV', value: LYVERA_MAIN_NAV },
      { name: 'LYVERA_FOOTER_LEGAL', value: LYVERA_FOOTER_LEGAL },
      { name: 'LYVERA_FOOTER_TAGLINE', value: LYVERA_FOOTER_TAGLINE },
      { name: 'LYVERA_FOOTER_USEFUL_LINKS', value: LYVERA_FOOTER_USEFUL_LINKS },
      { name: 'LYVERA_SOCIAL', value: LYVERA_SOCIAL },
      { name: 'LYVERA_BANNER_WHY_DEFAULT', value: LYVERA_BANNER_WHY_DEFAULT },
      { name: 'LYVERA_HERO_DEFAULT', value: LYVERA_HERO_DEFAULT },
    ]
  },
  {
    module: '@/lib/placeholder-utils',
    exports: [
      { name: 'placeholderHasComponents', value: placeholderHasComponents },
      { name: 'resolveChildPlaceholderKey', value: resolveChildPlaceholderKey },
      { name: 'getPlaceholderSlots', value: getPlaceholderSlots },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: '@/lib/lyvera-blog-content',
    exports: [
      { name: 'LYVERA_BLOG_ARTICLES', value: LYVERA_BLOG_ARTICLES },
      { name: 'LYVERA_BLOG_LISTING', value: LYVERA_BLOG_LISTING },
      { name: 'findBlogArticleByPath', value: findBlogArticleByPath },
    ]
  },
  {
    module: '@/lib/lyvera-sites',
    exports: [
      { name: 'getPublicItemPath', value: getPublicItemPath },
    ]
  },
  {
    module: '@/lib/lyvera-brand-pages',
    exports: [
      { name: 'findBrandPageByPath', value: findBrandPageByPath },
    ]
  },
  {
    module: '@/lib/demo-auth',
    exports: [
      { name: 'useDemoAuth', value: useDemoAuth },
      { name: 'DEMO_EMAIL', value: DEMO_EMAIL },
      { name: 'DemoAuthProvider', value: DemoAuthProvider },
    ]
  },
  {
    module: '@/components/demo/DemoSiteLabelSync',
    exports: [
      { name: 'DemoSiteLabelSync', value: DemoSiteLabelSync },
    ]
  },
  {
    module: '@/components/lyvera/HeaderDemoAuth',
    exports: [
      { name: 'HeaderDemoAuth', value: HeaderDemoAuth },
    ]
  },
  {
    module: '@/lib/lyvera-faq-content',
    exports: [
      { name: 'LYVERA_FAQ_HEADING', value: LYVERA_FAQ_HEADING },
      { name: 'LYVERA_FAQ_ITEMS', value: LYVERA_FAQ_ITEMS },
    ]
  },
  {
    module: 'src/components/lyvera/LyveraFacilityChooser',
    exports: [
      { name: 'useFacilityChooserContext', value: useFacilityChooserContext },
    ]
  },
  {
    module: '@/lib/keith-prowse-blog-content',
    exports: [
      { name: 'KP_BLOG_ARTICLES', value: KP_BLOG_ARTICLES },
      { name: 'KP_BLOG_LISTING', value: KP_BLOG_LISTING },
    ]
  },
  {
    module: '@/components/cdp-profile-panel/CdpSubscribeButton',
    exports: [
      { name: 'CdpSubscribeButton', value: CdpSubscribeButton },
    ]
  },
  {
    module: '@/components/lyvera/DemoLoginModal',
    exports: [
      { name: 'DemoLoginModal', value: DemoLoginModal },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image_5d8ce56058442d94361877e28c501c951a554a6a },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-cloudsdk/events/browser',
    exports: [
      { name: 'pageView', value: pageView },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: '@/shadcn/lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: '@/lib/cdp/cdp-identity',
    exports: [
      { name: 'displayNameFromEmail', value: displayNameFromEmail },
      { name: 'EMAIL_REGEX', value: EMAIL_REGEX },
      { name: 'identifyVisitorByEmail', value: identifyVisitorByEmail },
    ]
  },
  {
    module: '@/components/cdp-profile-panel/CdpProfilePanel',
    exports: [
      { name: 'CdpProfilePanel', value: CdpProfilePanel },
    ]
  },
  {
    module: '@/components/cdp-profile-panel/CdpPageViewTracker',
    exports: [
      { name: 'CdpPageViewTracker', value: CdpPageViewTracker },
    ]
  },
  {
    module: 'next/router',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: '@/lib/cdp/cdp-cloud-context',
    exports: [
      { name: 'loadCdpGuestProfile', value: loadCdpGuestProfile },
    ]
  },
  {
    module: '@/lib/cdp/sitecore-cookie-reset',
    exports: [
      { name: 'resetSitecoreVisitorSession', value: resetSitecoreVisitorSession },
    ]
  },
  {
    module: '@/lib/cdp/cdp-session-tracker',
    exports: [
      { name: 'recordPageView', value: recordPageView },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
