---
ID: "a9c85601-033a-4514-9877-7148949b22ec"
Parent: "a780bcf0-567e-4df5-8cff-8724ad1e512b"
Template: "a780bcf0-567e-4df5-8cff-8724ad1e512b"
Path: /sitecore/templates/Project/brother/ProductDetail Templates/ProductDetail Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
