---
ID: "767556f6-d793-4d07-bfe9-9d0070da80b0"
Parent: "030fc725-f21b-4e93-9fb8-e6ffb34cc22b"
Template: "030fc725-f21b-4e93-9fb8-e6ffb34cc22b"
Path: "/sitecore/templates/Project/automobile/Footer Templates/Footer Folder/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {CA57BA97-2A7B-4E69-B611-41ADF985E43A}
    {030FC725-F21B-4E93-9FB8-E6FFB34CC22B}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
