---
ID: "1fd74740-eb70-421d-aa87-0ec0eb8ed3f6"
Parent: "bf0987a9-a515-4e55-8d76-15df29bdb695"
Template: "bf0987a9-a515-4e55-8d76-15df29bdb695"
Path: "/sitecore/templates/Project/brother/FeatureGrid Templates/FeatureGrid/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
