---
ID: "2b7c1143-16f5-4721-8c82-17bc1d585e66"
Parent: "d05351e5-cf0e-49c0-88a2-707d9feb6b0d"
Template: "d05351e5-cf0e-49c0-88a2-707d9feb6b0d"
Path: /sitecore/templates/Project/brother/HeroBanner Templates/HeroBanner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
