---
ID: "2b374dba-d02b-4a0d-b900-457a25c8351d"
Parent: "a10417b4-1959-49d3-ba42-5ded252b69c7"
Template: "a10417b4-1959-49d3-ba42-5ded252b69c7"
Path: "/sitecore/templates/Project/automobile/ExploreCtaStrip Templates/ExploreCtaStrip Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260101T120000Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
